# Generated by Django 5.2.6 on 2025-09-26 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('text', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('font_size', models.IntegerField(default=16)),
                ('font_weight', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('lighter', 'Light')], default='normal', max_length=20)),
                ('font_style', models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italic')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time'],
                'unique_together': {('user', 'date', 'time')},
            },
        ),
    ]
